### PR TITLE
Adds tests for app and changes app so it is testable

### PR DESCRIPTION
**Pull request by alexwendte**
Associated Issue: #19 

### Summary of Changes

- Adds tests for app and changes app so it is testable
- Had to change .eslintrc to include afterEach as a global
- Had to change package.json so jest would include __mocks__
- Had to mock imported styles in __mocks__/styleMock.js

### CODE REVIEW

**Comment by ollelauribostrom** [comment]
Really great job @themostcolm 👍 

Some minor stuff before I can merge this:
- To remove any possible confusion, rename `export const app` to something `export function init() {...}`. 
- Call the`init` function from `app.js` to render the app. (Preferably only during production)
- I'm also thinking that the second test case might be redundant (by looking at the snapshot file)

**Comment by themostcolm** [comment]
How do I do this?

Call the init function to render the app. (Preferably only during production)

**Comment by ollelauribostrom** [comment]
We could add a global to out jest config (in package.json):

```
"jest": {
    "globals": {
       "isTestRun": true,
     },
     ...
},
```

And then do (in app.js)

```js
if (!global || !global.isTestRun) {
  init()
}
```

**Comment by alexwendte** [comment]
Is that what you mean?

**Comment by ollelauribostrom** [comment]
@alexwendte Yes, that should work! If you can just fix the lint error, I will merge this 🙂

**Comment by ollelauribostrom** [comment]
Thanks for the patch! 🙂

**Pull request merged**
